build: off

environment:
  nodejs_version: "7.4.0"

install:
  - git submodule update --init --recursive
  - yarn install-node-obs
  - yarn install
  - yarn ci:compile

test_script:
  - yarn test -- -v
