build: off

install:
  - ps: Install-Product node 8
  - git submodule update --init --recursive
  - yarn install
  - yarn install-plugins
  - yarn ci:compile

test_script:
  - yarn screentest

artifacts:
  - path: 'test-dist\screentest\**\*'
    name: Screentests